apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
spec:
  destination:
    namespace: <ns to deploy to>
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/agumbe-ai/kargo-demo-manifests-index.git
    targetRevision: <branch>
    path: infra/k8s/auth/overlays/<stage>
  project: kargo-demo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
