apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: kargo-demo-manifests  
    namespace: test  
    labels:
        kargo.akuity.io/secret-type: repository
stringData:
    type: git  
    project: kargo-demo  
    url: ${GITOPS_REPO_URL}  
    username: ${GITHUB_USERNAME}  
    password: ${GITHUB_PAT}
