apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: test
spec:
  subscriptions:
    upstreamStages:
    - name: uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/agumbe-ai/kargo-demo-manifests.git
      writeBranch: prod
      kustomize:
        images:
        - image: nginx
          path: infra/k8s/auth/stages/prod
    argoCDAppUpdates:
    - appName: auth
      appNamespace: test